// Actor context builders
export { SOLO_ACTOR, mcpActor, aiPmActor, remoteMcpActor } from "./actor";

// P08B: session token sign/verify (stateless HMAC cookie).
export { signSession, verifySession, type SessionPayload } from "./auth/session";

// Token encryption (P07D) — AES-256-GCM for provider tokens in config_json.
export {
  encryptSecret,
  decryptSecret,
  isEncrypted,
  generateKeyB64,
  CryptoError,
  type CryptoOpts,
} from "./crypto";

// Re-exported types from @statehub/db so consumers can import from one place.
export {
  type ActorContext,
  type EventType,
  type Workspace,
  type Project,
  type ProjectType,
  type ProjectStatus,
  type PortfolioPriority,
  type ProjectRepoAlias,
  type State,
  type StatusGroup,
  type Label,
  type Feature,
  type FeatureStatus,
  type WorkItem,
  type WorkItemType,
  type Priority,
  type ConfidenceLevel,
  type WorkItemSource,
  type View,
  type ViewLayout,
  type Cycle,
  type CycleStatus,
  type AgentRun,
  type AgentRunStatus,
  type EvidenceTrustState,
  type Todo,
  type TodoStatus,
  type TodoType,
  type Evidence,
  type EvidenceType,
  type EvidenceStalenessState,
  type TokenScope,
  type DbClient,
  type SqlStmt,
  type SqlBindValue,
  type Review,
  type ReviewVerdict,
  type ReviewFinding,
  type FindingSeverity,
  type FindingStatus,
  type AiPmActionCard,
  type ActionCardStatus,
  type Decision,
  type DecisionSource,
  type WeeklyReview,
  type ExternalLink,
  type ExternalSource,
  type ExternalLinkStatus,
  type Integration,
  type IntegrationProvider,
  type IntegrationStatus,
  type ImportJob,
  type ImportJobStatus,
} from "@statehub/db";

// Domain errors
export {
  DomainError,
  NotFoundError,
  AlreadyExistsError,
  ConflictError,
  RepoConflictError,
  ValidationError,
  ForbiddenError,
  rethrowUniqueViolation,
} from "./errors";

// Services
export {
  authService,
  type AuthService,
  requireUser,
  sequenceService,
  type SequenceService,
  workspaceService,
  type WorkspaceService,
  type CreateWorkspaceInput,
  type UpdateWorkspaceInput,
  projectService,
  type ProjectService,
  type CreateProjectInput,
  type UpdateProjectInput,
  stateService,
  type StateService,
  type CreateStateInput,
  type UpdateStateInput,
  labelService,
  type LabelService,
  type CreateLabelInput,
  type UpdateLabelInput,
  featureService,
  type FeatureService,
  type CreateFeatureInput,
  type UpdateFeatureInput,
  workItemService,
  type WorkItemService,
  type CreateWorkItemInput,
  type UpdateWorkItemInput,
  type UpsertWorkItemInput,
  type UpsertWorkItemResult,
  type ListWorkItemsFilter,
  type EventRow,
  viewService,
  type ViewService,
  type CreateViewInput,
  type UpdateViewInput,
  type ViewQuery,
  type ViewDisplay,
  parseViewQuery,
  parseViewDisplay,
  cycleService,
  type CycleService,
  type CreateCycleInput,
  projectHealthService,
  type ProjectHealthService,
  type ProjectHealthSummary,
  type PortfolioHealth,
  type HealthFocus,
  type HealthNextAction,
  type AtRiskProject,
  PORTFOLIO_PRIORITY_RANK,
  tokenService,
  type TokenService,
  type IssuedToken,
  type VerifiedToken,
  requireScope,
  idempotencyService,
  type IdempotencyService,
  type IdempotencyHit,
  hashRequest,
  agentRunService,
  type AgentRunService,
  type StartAgentRunInput,
  type CompleteAgentRunInput,
  todoService,
  type TodoService,
  type CreateTodoInput,
  type UpdateTodoStatusInput,
  type UpsertTodoInput,
  type UpsertTodoResult,
  evidenceService,
  type EvidenceService,
  type CreateEvidenceInput,
  doneGateService,
  type DoneGateService,
  type DoneGateSummary,
  type DoneGateWarning,
  type DoneGateChecklistItem,
  type DoneGateInput,
  mcpSyncService,
  type McpSyncService,
  type McpSyncState,
  type McpSyncSummary,
  reviewService,
  type ReviewService,
  type ReviewFindingInput,
  type SubmitReviewInput,
  type SubmitReviewResult,
  type TransitionFindingInput,
  type CreateFollowupFixesInput,
  type CreateFollowupFixesResult,
  type CreatedFix,
  type SkippedFinding,
  type ListReviewsFilter,
  repoAliasService,
  type RepoAliasService,
  localEvidenceService,
  type LocalEvidenceService,
  type IngestLocalEvidenceInput,
  type IngestLocalEvidenceResult,
  type RepoMatchStatus,
  decisionService,
  type DecisionService,
  type RecordDecisionInput,
  weeklyReviewService,
  type WeeklyReviewService,
  type SaveWeeklyReviewInput,
  actionCardService,
  type ActionCardService,
  type ApplyResult,
  validateActionForApply,
  DoneGateBlockedError,
  HighRiskConfirmationRequiredError,
  ACTION_VALIDATORS,
  type ActionValidator,
  type ActionValidatorContext,
  createAiPmService,
  aiPmService,
  type AIPmService,
  type AIPmQueryInput,
  type AIPmQueryResult,
  type AIPmServiceOptions,
  type AIPmMode,
  type AnswerEnvelope,
  type ContextPacket,
  externalLinkService,
  type ExternalLinkService,
  type CreateExternalLinkInput,
  exportProject,
  type MarkdownExportOptions,
  type MarkdownExportResult,
  integrationService,
  type IntegrationService,
  type CreateIntegrationInput,
  type UpdateIntegrationInput,
  githubIssuesImporter,
  type GithubIssuesImporter,
  type GithubIssue,
  type ImportInput,
  type ImportPreview,
  type ImportPreviewItem,
  type ImportSkipItem,
  type ImportErrorItem,
  type ImportRunResult,
  type ImportRunItem,
  listImportJobs,
  getImportJob,
  planeIssuesImporter,
  type PlaneIssuesImporter,
  type PlaneIssue,
  linearIssuesImporter,
  type LinearIssuesImporter,
  type LinearIssue,
} from "./services";

// Row mappers (for raw row -> typed object conversion in API routes)
export {
  mapWorkspace,
  mapProject,
  mapProjectRepoAlias,
  mapState,
  mapLabel,
  mapFeature,
  mapWorkItem,
  mapView,
  mapCycle,
  mapAgentRun,
  mapTodo,
  mapEvidence,
  mapReview,
  mapReviewFinding,
  mapAiPmActionCard,
  mapDecision,
  mapWeeklyReview,
  mapExternalLink,
  mapIntegration,
  mapImportJob,
} from "./mappers";
